### ISSUE TITLE
message size

### ISSUE THREAD

**Issue by seriouslylost** [xx10t4/iota1k#13]
How large can i make a message? Possible to transmit data? Files? pictures?

regards,
helge

**Comment by xx10t4** [comment]
The NTRU encryption limits messages to 106 characters currently. I will probably switch to using the IOTA standard MAM encryption at some point soon, which will allow for longer messages. 

Transmitting files is a planned feature as well, but there are some speed vs privacy tradeoffs to be considered with regard to sending large amounts of data - storing such data in the Tangle itself would work well for privacy but could be extremely slow since it would require many transactions, each of which requires POW processing. Storing the data off of the Tangle is another option, but could introduce privacy issues if a centralized system is used. The overall arching principle of iota1k is that communications should be private so I want to make sure that features like file attachments are done correctly in support of that goal.
