### ISSUE TITLE
account name duplication

### ISSUE THREAD

**Issue by seriouslylost** [xx10t4/iota1k#8]
it is possible to have same account name, only the code behind the @ changes. This is suboptimal

**Comment by xx10t4** [comment]
Yes it is not ideal but this is due to the nature of how data is stored in the Tangle. The part AFTER the @ is in fact is the only part of the account name that the app actually cares about as it is the unique fingerprint for that account's public key. The part before the @ is just a human readable tag used for displaying accounts and contacts. 

Just as there can be joe@gmail.com and joe@yahoo.com email addresses, the part before the @ is not unique.
